server:
  port: 3000

spring:
  application:
    name: practice-keycloak
  config:
    import: optional:file:.env.dev[.properties]

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    open-in-view: false
    generate-ddl: true

  # ???? - oauth2??
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak1.sparta-project.xyz/realms/sparta
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/v1/users/authorization/code"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: https://keycloak1.sparta-project.xyz/realms/sparta

keycloak:
  server-url: https://keycloak1.sparta-project.xyz
  realm: sparta
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}